"""PostgreSQL registry persistence with atomic revisions and LKG fallback.

This module is the configuration persistence boundary.  The existing
``storage.py`` runtime store remains intentionally separate and cannot contain
registry configuration or runtime-derived writes.
"""

from __future__ import annotations

import inspect
import asyncio
import json
import logging
from contextlib import asynccontextmanager
from copy import deepcopy
from dataclasses import replace
from datetime import datetime
from typing import Any, AsyncIterator, Callable, Iterable, Mapping, Protocol
from uuid import UUID, uuid4

from .const import (
    REGISTRY_CACHE_SCHEMA_VERSION,
    SUPPORTED_REGISTRY_SCHEMA_VERSIONS,
)
from .models import ProfileId
from .quality import HealthStatus, utc_now
from .registry import (
    ConcurrencyConflict,
    RegistryCorruptionError,
    RegistryError,
    RegistryLoadResult,
    RegistryPayload,
    RegistryRevision,
    RegistrySource,
    RevisionNotFound,
    RevisionStateError,
    RegistryValidationError,
    RevisionStatus,
    RevisionValidationFailed,
    canonical_registry_json,
    registry_checksum,
    validate_registry_payload,
)


LOGGER = logging.getLogger(__name__)

REGISTRY_TABLE = "core_contracts_registry_revision"

REGISTRY_MIGRATION_SQL = f"""
CREATE TABLE IF NOT EXISTS {REGISTRY_TABLE} (
    id UUID PRIMARY KEY,
    revision BIGINT GENERATED BY DEFAULT AS IDENTITY,
    profile TEXT NOT NULL CHECK (profile IN ('benni', 'eltern')),
    schema_version INTEGER NOT NULL CHECK (schema_version > 0),
    payload JSONB NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('draft', 'active', 'superseded', 'rejected')),
    created_at TIMESTAMPTZ NOT NULL,
    activated_at TIMESTAMPTZ,
    checksum TEXT NOT NULL CHECK (checksum ~ '^[0-9a-f]{{64}}$'),
    created_by TEXT,
    CHECK (
        (status IN ('active', 'superseded') AND activated_at IS NOT NULL)
        OR (status IN ('draft', 'rejected') AND activated_at IS NULL)
    ),
    UNIQUE (profile, revision)
);

CREATE UNIQUE INDEX IF NOT EXISTS {REGISTRY_TABLE}_one_active_per_profile
    ON {REGISTRY_TABLE} (profile)
    WHERE status = 'active';

CREATE INDEX IF NOT EXISTS {REGISTRY_TABLE}_profile_revision_idx
    ON {REGISTRY_TABLE} (profile, revision DESC);
""".strip()

_SELECT_COLUMNS = """
    id, revision, profile, schema_version, payload, status,
    created_at, activated_at, checksum, created_by
""".strip()

_SELECT_BY_ID = f"""
SELECT {_SELECT_COLUMNS}
FROM {REGISTRY_TABLE}
WHERE id = $1
""".strip()

_SELECT_BY_ID_FOR_UPDATE = f"""
SELECT {_SELECT_COLUMNS}
FROM {REGISTRY_TABLE}
WHERE id = $1
FOR UPDATE
""".strip()

_SELECT_ACTIVE = f"""
SELECT {_SELECT_COLUMNS}
FROM {REGISTRY_TABLE}
WHERE profile = $1 AND status = 'active'
ORDER BY revision DESC
LIMIT 1
FOR UPDATE
""".strip()

_SELECT_ALL = f"""
SELECT {_SELECT_COLUMNS}
FROM {REGISTRY_TABLE}
ORDER BY profile, revision
""".strip()

_SELECT_PROFILE = f"""
SELECT {_SELECT_COLUMNS}
FROM {REGISTRY_TABLE}
WHERE profile = $1
ORDER BY revision
""".strip()

_INSERT_REVISION = f"""
INSERT INTO {REGISTRY_TABLE}
    (id, profile, schema_version, payload, status, created_at, checksum, created_by)
VALUES ($1, $2, $3, $4::jsonb, $5, $6, $7, $8)
RETURNING {_SELECT_COLUMNS}
""".strip()

_REJECT_REVISION = f"""
UPDATE {REGISTRY_TABLE}
SET status = 'rejected'
WHERE id = $1 AND status = 'draft'
""".strip()

_SUPERSEDE_REVISION = f"""
UPDATE {REGISTRY_TABLE}
SET status = 'superseded'
WHERE id = $1 AND status = 'active'
""".strip()

_ACTIVATE_REVISION = f"""
UPDATE {REGISTRY_TABLE}
SET status = 'active', activated_at = $2
WHERE id = $1 AND status IN ('draft', 'superseded')
RETURNING {_SELECT_COLUMNS}
""".strip()

_LOCK_PROFILE = "SELECT pg_advisory_xact_lock(hashtext($1))"


class PostgresUnavailableError(RegistryError):
    """The PostgreSQL repository could not complete an operation."""


class RegistryStoreError(RegistryError):
    """The repository returned an impossible or incomplete result."""


class LastKnownGoodBackend(Protocol):
    async def async_load(self) -> dict[str, Any] | None: ...

    async def async_save(self, data: dict[str, Any]) -> None: ...


class LastKnownGoodCache(Protocol):
    async def async_load(self, profile: ProfileId) -> RegistryRevision | None: ...

    async def async_save(self, revision: RegistryRevision) -> None: ...


class LastKnownGoodCodec:
    """Encode only successfully activated registry revisions for local use."""

    @staticmethod
    def encode(revisions: Iterable[RegistryRevision]) -> dict[str, Any]:
        by_profile: dict[str, dict[str, Any]] = {}
        for revision in revisions:
            by_profile[revision.profile.value] = revision.as_cache_dict()
        return {
            "cache_version": REGISTRY_CACHE_SCHEMA_VERSION,
            "revisions": by_profile,
        }

    @staticmethod
    def decode_all(data: Mapping[str, Any]) -> dict[ProfileId, RegistryRevision]:
        if not isinstance(data, Mapping):
            raise RegistryCorruptionError("Last-Known-Good payload must be an object")
        if set(data) != {"cache_version", "revisions"}:
            raise RegistryCorruptionError(
                "Last-Known-Good payload contains unknown or missing fields"
            )
        try:
            version = int(data["cache_version"])
        except (TypeError, ValueError) as err:
            raise RegistryCorruptionError("invalid Last-Known-Good cache version") from err
        if version != REGISTRY_CACHE_SCHEMA_VERSION:
            raise RegistryCorruptionError(
                f"unsupported Last-Known-Good cache version: {version}"
            )
        raw_revisions = data["revisions"]
        if not isinstance(raw_revisions, Mapping):
            raise RegistryCorruptionError("Last-Known-Good revisions must be an object")
        decoded: dict[ProfileId, RegistryRevision] = {}
        for profile_value, raw_revision in raw_revisions.items():
            try:
                profile = ProfileId(str(profile_value))
            except ValueError as err:
                raise RegistryCorruptionError(
                    f"unsupported Last-Known-Good profile: {profile_value}"
                ) from err
            if not isinstance(raw_revision, Mapping):
                raise RegistryCorruptionError("Last-Known-Good revision must be an object")
            try:
                revision = RegistryRevision.from_dict(raw_revision)
            except (RegistryError, ValueError) as err:
                raise RegistryCorruptionError(
                    f"invalid Last-Known-Good revision for {profile.value}"
                ) from err
            if revision.profile != profile or revision.status != RevisionStatus.ACTIVE:
                raise RegistryCorruptionError(
                    f"Last-Known-Good profile/status mismatch for {profile.value}"
                )
            if revision.schema_version not in SUPPORTED_REGISTRY_SCHEMA_VERSIONS:
                raise RegistryCorruptionError("unsupported Last-Known-Good revision schema")
            decoded[profile] = revision
        return decoded

    @staticmethod
    def decode(
        data: Mapping[str, Any], profile: ProfileId | str
    ) -> RegistryRevision | None:
        profile_id = profile if isinstance(profile, ProfileId) else ProfileId(str(profile))
        if not isinstance(data, Mapping) or set(data) != {'cache_version','revisions'} or not isinstance(data.get('revisions'), Mapping):
            raise RegistryCorruptionError('invalid Last-Known-Good envelope')
        # One corrupt household must not make the other household's LKG unreadable.
        selected = data['revisions'].get(profile_id.value)
        envelope = {'cache_version': data['cache_version'], 'revisions': {profile_id.value:selected} if selected is not None else {}}
        return LastKnownGoodCodec.decode_all(envelope).get(profile_id)


class PersistentLastKnownGoodCache:
    """Store the LKG envelope on a local async backend such as HA Store."""

    def __init__(self, backend: LastKnownGoodBackend) -> None:
        self._backend = backend
        self._lock = asyncio.Lock()

    async def async_load(self, profile: ProfileId) -> RegistryRevision | None:
        data = await self._backend.async_load()
        if not data:
            return None
        return LastKnownGoodCodec.decode(data, profile)

    async def async_save(self, revision: RegistryRevision) -> None:
        async with self._lock:
            existing = await self._backend.async_load()
            records = deepcopy(existing.get('revisions',{})) if existing else {}
            records[revision.profile.value] = revision.as_cache_dict()
            await self._backend.async_save({'cache_version':REGISTRY_CACHE_SCHEMA_VERSION,'revisions':records})


class InMemoryLastKnownGoodCache:
    """Deterministic local cache used by repository tests and adapters."""

    def __init__(self, data: dict[str, Any] | None = None) -> None:
        self.data = deepcopy(data)

    async def async_load(self, profile: ProfileId) -> RegistryRevision | None:
        if not self.data:
            return None
        return LastKnownGoodCodec.decode(self.data, profile)

    async def async_save(self, revision: RegistryRevision) -> None:
        revisions = LastKnownGoodCodec.decode_all(self.data) if self.data else {}
        revisions[revision.profile] = revision
        self.data = LastKnownGoodCodec.encode(revisions.values())


class HomeAssistantLastKnownGoodCache(PersistentLastKnownGoodCache):
    """Local HA Store adapter with a registry-specific cache schema/key."""

    def __init__(self, hass: Any, key: str) -> None:
        from homeassistant.helpers.storage import Store

        super().__init__(
            _HomeAssistantStoreBackend(
                Store(hass, REGISTRY_CACHE_SCHEMA_VERSION, key)
            )
        )


class _HomeAssistantStoreBackend:
    def __init__(self, store: Any) -> None:
        self._store = store

    async def async_load(self) -> dict[str, Any] | None:
        return await self._store.async_load()

    async def async_save(self, data: dict[str, Any]) -> None:
        await self._store.async_save(data)


async def _maybe_await(value: Any) -> Any:
    if inspect.isawaitable(value):
        return await value
    return value


@asynccontextmanager
async def _transaction(connection: Any) -> AsyncIterator[Any]:
    transaction_factory = getattr(connection, "transaction", None)
    if not callable(transaction_factory):
        # Lightweight fakes may not expose transactions; asyncpg connections do.
        yield connection
        return
    async with transaction_factory():
        yield connection


class PostgresRegistryRepository:
    """Repository for canonical JSONB registry revisions.

    ``database`` may be an asyncpg pool or a connection.  The repository never
    accepts runtime signals as a registry payload and every activation locks
    the profile's active row before comparing the expected base revision.
    """

    def __init__(
        self,
        database: Any,
        *,
        lkg_cache: LastKnownGoodCache | None = None,
        schema_registry: Any | None = None,
        validator: Callable[[RegistryPayload], Any] | None = None,
        now_factory: Callable[[], datetime] = utc_now,
    ) -> None:
        self._database = database
        self._lkg_cache = lkg_cache
        self._schema_registry = schema_registry
        self._validator = validator
        self._now_factory = now_factory

    @asynccontextmanager
    async def _connection(self) -> AsyncIterator[Any]:
        acquire = getattr(self._database, "acquire", None)
        if not callable(acquire):
            yield self._database
            return
        acquired = acquire()
        if hasattr(acquired, "__aenter__"):
            async with acquired as connection:
                yield connection
            return
        connection = await _maybe_await(acquired)
        try:
            yield connection
        finally:
            release = getattr(self._database, "release", None)
            if callable(release):
                await _maybe_await(release(connection))

    def _validate(self, payload: RegistryPayload) -> RegistryPayload:
        if self._validator is not None:
            result = self._validator(payload)
            return result if isinstance(result, RegistryPayload) else payload
        return validate_registry_payload(
            payload,
            schema_registry=self._schema_registry,
        )

    @staticmethod
    def _profile(value: ProfileId | str) -> ProfileId:
        return value if isinstance(value, ProfileId) else ProfileId(str(value))

    @staticmethod
    def _db_id(value: str | UUID) -> UUID | str:
        try:
            return value if isinstance(value, UUID) else UUID(str(value))
        except (AttributeError, TypeError, ValueError):
            return str(value)

    async def async_migrate(self) -> None:
        """Apply the idempotent PostgreSQL migration explicitly."""

        try:
            async with self._connection() as connection:
                async with _transaction(connection):
                    await connection.execute(REGISTRY_MIGRATION_SQL)
        except Exception as err:
            raise PostgresUnavailableError("PostgreSQL migration failed") from err

    async def create_revision(
        self,
        payload: RegistryPayload | Mapping[str, Any],
        *,
        profile: ProfileId | str | None = None,
        created_by: str | None = None,
    ) -> RegistryRevision:
        """Persist a new draft without touching the currently active revision."""

        try:
            normalized = (
                payload
                if isinstance(payload, RegistryPayload)
                else RegistryPayload.from_dict(payload)
            )
            if profile is not None and self._profile(profile) != normalized.profile:
                raise RegistryValidationError(
                    "create_revision profile does not match payload profile"
                )
            revision_id = uuid4()
            created_at = self._now_factory()
            payload_json = canonical_registry_json(normalized)
            checksum = registry_checksum(normalized)
            async with self._connection() as connection:
                async with _transaction(connection):
                    row = await connection.fetchrow(
                        _INSERT_REVISION,
                        revision_id,
                        normalized.profile.value,
                        normalized.schema_version,
                        payload_json,
                        RevisionStatus.DRAFT.value,
                        created_at,
                        checksum,
                        created_by,
                    )
            if row is None:
                raise RegistryStoreError("PostgreSQL did not return the new revision")
            return _revision_from_row(row)
        except (RegistryError, ValueError):
            raise
        except Exception as err:
            raise PostgresUnavailableError("PostgreSQL revision creation failed") from err

    async def get_revision(self, revision_id: str | UUID) -> RegistryRevision | None:
        try:
            async with self._connection() as connection:
                row = await connection.fetchrow(_SELECT_BY_ID, self._db_id(revision_id))
            return _revision_from_row(row) if row is not None else None
        except RegistryError:
            raise
        except Exception as err:
            raise PostgresUnavailableError("PostgreSQL revision read failed") from err

    async def read_revision(self, revision_id: str | UUID) -> RegistryRevision | None:
        return await self.get_revision(revision_id)

    async def get_active_revision(self, profile: ProfileId | str) -> RegistryRevision | None:
        profile_id = self._profile(profile)
        try:
            async with self._connection() as connection:
                row = await connection.fetchrow(_SELECT_ACTIVE, profile_id.value)
            return _revision_from_row(row) if row is not None else None
        except RegistryError:
            raise
        except Exception as err:
            raise PostgresUnavailableError("PostgreSQL active revision read failed") from err

    async def read_active_revision(self, profile: ProfileId | str) -> RegistryRevision | None:
        return await self.get_active_revision(profile)

    async def list_revisions(
        self,
        profile: ProfileId | str | None = None,
    ) -> tuple[RegistryRevision, ...]:
        profile_id = self._profile(profile) if profile is not None else None
        try:
            async with self._connection() as connection:
                rows = await connection.fetch(
                    _SELECT_PROFILE if profile_id is not None else _SELECT_ALL,
                    profile_id.value,
                ) if profile_id is not None else await connection.fetch(_SELECT_ALL)
            return tuple(_revision_from_row(row) for row in rows)
        except RegistryError:
            raise
        except Exception as err:
            raise PostgresUnavailableError("PostgreSQL revision history read failed") from err

    async def activate_revision(
        self,
        revision_id: str | UUID,
        expected_base_revision: int | None = None,
    ) -> RegistryRevision:
        """Validate and atomically activate a draft or historical revision."""

        if expected_base_revision is not None:
            if (
                isinstance(expected_base_revision, bool)
                or not isinstance(expected_base_revision, int)
                or expected_base_revision < 0
            ):
                raise ValueError("expected_base_revision must be a non-negative integer")

        validation_failure: RevisionValidationFailed | None = None
        activated: RegistryRevision | None = None
        try:
            async with self._connection() as connection:
                async with _transaction(connection):
                    candidate_row = await connection.fetchrow(
                        _SELECT_BY_ID_FOR_UPDATE,
                        self._db_id(revision_id),
                    )
                    if candidate_row is None:
                        raise RevisionNotFound(f"registry revision not found: {revision_id}")
                    candidate = _revision_from_row(candidate_row)
                    await connection.execute(_LOCK_PROFILE, candidate.profile.value)
                    active_row = await connection.fetchrow(
                        _SELECT_ACTIVE,
                        candidate.profile.value,
                    )
                    active = _revision_from_row(active_row) if active_row is not None else None
                    current_base_revision = active.revision if active is not None else 0
                    if (
                        expected_base_revision is not None
                        and expected_base_revision != current_base_revision
                    ):
                        raise ConcurrencyConflict(
                            expected_base_revision,
                            current_base_revision,
                        )
                    if candidate.status == RevisionStatus.REJECTED:
                        raise RevisionStateError(
                            f"rejected revision cannot be activated: {candidate.revision}"
                        )
                    if candidate.status == RevisionStatus.ACTIVE:
                        if active is None or active.id != candidate.id:
                            raise RevisionStateError(
                                "active revision does not match the profile active row"
                            )
                    else:
                        try:
                            self._validate(candidate.payload)
                        except Exception as err:
                            validation_failure = RevisionValidationFailed(
                                candidate.revision,
                                str(err) or type(err).__name__,
                            )
                            if candidate.status == RevisionStatus.DRAFT:
                                await connection.execute(
                                    _REJECT_REVISION,
                                    self._db_id(candidate.id),
                                )
                        else:
                            if active is not None and active.id != candidate.id:
                                await connection.execute(
                                    _SUPERSEDE_REVISION,
                                    self._db_id(active.id),
                                )
                            activated_row = await connection.fetchrow(
                                _ACTIVATE_REVISION,
                                self._db_id(candidate.id),
                                self._now_factory(),
                            )
                            if activated_row is None:
                                raise RevisionStateError(
                                    f"revision is not activatable: {candidate.revision}"
                                )
                            activated = _revision_from_row(activated_row)
                    if candidate.status == RevisionStatus.ACTIVE:
                        activated = candidate
            if validation_failure is not None:
                raise validation_failure
            if activated is None:
                raise RegistryStoreError("activation produced no revision")
        except (RegistryError, RevisionValidationFailed):
            raise
        except Exception as err:
            raise PostgresUnavailableError("PostgreSQL revision activation failed") from err

        await self._save_lkg_best_effort(activated)
        return activated

    async def rollback_revision(
        self,
        revision_id: str | UUID,
        expected_base_revision: int | None = None,
    ) -> RegistryRevision:
        """Reactivate a non-rejected historical revision without deleting history."""

        return await self.activate_revision(revision_id, expected_base_revision)

    async def rollback(
        self,
        profile: ProfileId | str,
        revision_id: str | UUID,
        expected_base_revision: int | None = None,
    ) -> RegistryRevision:
        candidate = await self.get_revision(revision_id)
        if candidate is None:
            raise RevisionNotFound(f"registry revision not found: {revision_id}")
        if candidate.profile != self._profile(profile):
            raise RevisionStateError("rollback revision belongs to another profile")
        return await self.activate_revision(revision_id, expected_base_revision)

    async def load_active(self, profile: ProfileId | str) -> RegistryLoadResult:
        """Read PostgreSQL first and use a validated LKG on connectivity failure."""

        profile_id = self._profile(profile)
        try:
            active = await self.get_active_revision(profile_id)
        except RegistryCorruptionError:
            return await self._load_lkg(
                profile_id,
                reason="postgres_active_revision_invalid",
            )
        except PostgresUnavailableError:
            return await self._load_lkg(
                profile_id,
                reason="postgres_unavailable",
            )
        if active is None:
            return RegistryLoadResult(
                profile=profile_id,
                revision=None,
                source=RegistrySource.NONE,
                health=HealthStatus.UNKNOWN,
                reason="no_active_revision",
            )
        try:
            self._validate(active.payload)
        except Exception:
            return await self._load_lkg(
                profile_id,
                reason="postgres_active_revision_invalid",
            )
        await self._save_lkg_best_effort(active)
        return RegistryLoadResult(
            profile=profile_id,
            revision=active,
            source=RegistrySource.POSTGRESQL,
            health=HealthStatus.HEALTHY,
        )

    async def load_active_with_fallback(
        self,
        profile: ProfileId | str,
    ) -> RegistryLoadResult:
        return await self.load_active(profile)

    async def _load_lkg(
        self,
        profile: ProfileId,
        *,
        reason: str,
    ) -> RegistryLoadResult:
        if self._lkg_cache is None:
            return RegistryLoadResult(
                profile=profile,
                revision=None,
                source=RegistrySource.NONE,
                health=HealthStatus.BLOCKED,
                reason=f"{reason}_no_last_known_good",
            )
        try:
            revision = await self._lkg_cache.async_load(profile)
            if revision is None:
                return RegistryLoadResult(
                    profile=profile,
                    revision=None,
                    source=RegistrySource.NONE,
                    health=HealthStatus.BLOCKED,
                    reason=f"{reason}_no_last_known_good",
                )
            if revision.profile != profile or revision.status != RevisionStatus.ACTIVE:
                raise RegistryCorruptionError("Last-Known-Good revision is not active")
            self._validate(revision.payload)
        except (RegistryCorruptionError, RegistryValidationError):
            return RegistryLoadResult(
                profile=profile,
                revision=None,
                source=RegistrySource.NONE,
                health=HealthStatus.BLOCKED,
                reason="last_known_good_invalid",
            )
        except Exception:
            return RegistryLoadResult(
                profile=profile,
                revision=None,
                source=RegistrySource.NONE,
                health=HealthStatus.BLOCKED,
                reason="last_known_good_unavailable",
            )
        return RegistryLoadResult(
            profile=profile,
            revision=revision,
            source=RegistrySource.LAST_KNOWN_GOOD,
            health=HealthStatus.DEGRADED,
            reason=reason,
        )

    async def _save_lkg_best_effort(self, revision: RegistryRevision) -> None:
        if self._lkg_cache is None:
            return
        try:
            await self._lkg_cache.async_save(replace(revision, status=RevisionStatus.ACTIVE))
        except Exception as err:
            # A cache write must never turn a committed PostgreSQL activation
            # into a reported failure; the active row remains authoritative.
            LOGGER.warning(
                "registry last-known-good cache update failed (%s)",
                type(err).__name__,
            )


def _row_value(row: Any, key: str) -> Any:
    try:
        return row[key]
    except (KeyError, IndexError, TypeError) as err:
        raise RegistryCorruptionError(f"registry row is missing {key}") from err


def _timestamp(value: Any, key: str) -> datetime:
    if isinstance(value, datetime):
        return value
    if isinstance(value, str):
        try:
            return datetime.fromisoformat(value)
        except ValueError as err:
            raise RegistryCorruptionError(f"registry row has invalid {key}") from err
    raise RegistryCorruptionError(f"registry row has invalid {key}")


def _payload_value(value: Any) -> Mapping[str, Any]:
    if isinstance(value, Mapping):
        return value
    if isinstance(value, (str, bytes, bytearray)):
        try:
            decoded = json.loads(value)
        except (TypeError, ValueError) as err:
            raise RegistryCorruptionError("registry row payload is not valid JSON") from err
        if isinstance(decoded, Mapping):
            return decoded
    raise RegistryCorruptionError("registry row payload must be a JSON object")


def _revision_from_row(row: Any) -> RegistryRevision:
    if row is None:
        raise RegistryCorruptionError("registry row is empty")
    try:
        raw_payload = _payload_value(_row_value(row, "payload"))
        payload = RegistryPayload.from_dict(raw_payload)
        stored_checksum = _row_value(row, "checksum")
        if not isinstance(stored_checksum, str) or not stored_checksum:
            raise RegistryCorruptionError("registry row checksum is missing")
        expected_checksum = registry_checksum(payload)
        if stored_checksum != expected_checksum:
            raise RegistryCorruptionError("registry row checksum mismatch")
        revision = RegistryRevision(
            id=str(_row_value(row, "id")),
            revision=int(_row_value(row, "revision")),
            profile=ProfileId(str(_row_value(row, "profile"))),
            schema_version=int(_row_value(row, "schema_version")),
            payload=payload,
            status=RevisionStatus(str(_row_value(row, "status"))),
            created_at=_timestamp(_row_value(row, "created_at"), "created_at"),
            activated_at=(
                _timestamp(_row_value(row, "activated_at"), "activated_at")
                if _row_value(row, "activated_at") is not None
                else None
            ),
            checksum=stored_checksum,
            created_by=(
                str(_row_value(row, "created_by"))
                if _row_value(row, "created_by") is not None
                else None
            ),
        )
        if revision.schema_version not in SUPPORTED_REGISTRY_SCHEMA_VERSIONS:
            raise RegistryCorruptionError("unsupported registry row schema version")
        return revision
    except RegistryCorruptionError:
        raise
    except (KeyError, TypeError, ValueError) as err:
        raise RegistryCorruptionError(f"invalid registry row: {err}") from err


# Naming aliases keep the repository layer discoverable without introducing a
# second persistence implementation.
PostgresRegistryStore = PostgresRegistryRepository
RegistryStore = PostgresRegistryRepository
