<script lang="ts">
  import { ArrowDownUp, ExternalLink, HelpCircle, Pencil } from '@lucide/svelte';
  import type { CoreContractsStore } from '../../lib/core-contracts/store.svelte';
  import { formatValue, labelForSchema } from '../../lib/core-contracts/format';
  import StatusBadge from '../../lib/ui/StatusBadge.svelte';
  let {store,onSelect,onDetail,onTrace,onEdit}:{store:CoreContractsStore;onSelect:(id:string)=>void;onDetail:(id:string)=>void;onTrace:(id:string,field:string)=>void;onEdit:()=>void}=$props();
  let rows=$derived([...store.filteredContracts.filter(item=>store.contractHealthFilter==='all'||item.health===store.contractHealthFilter)].sort((a,b)=>store.contractSort==='schema'?a.schema_id.localeCompare(b.schema_id):store.contractSort==='quality'?a.health.localeCompare(b.health):a.contract_id.localeCompare(b.contract_id)));
  let selected=$derived(store.selectedContract);
  const open=(id:string)=>store.preferences.openBehavior==='detail'?onDetail(id):onSelect(id);
</script>
<div class="explorer"><section class="list" aria-label="Vertrags-Explorer"><header><div><h2>Verträge</h2><p>{rows.length} von {store.contracts.length}</p></div><div class="filters"><label>Qualität<select value={store.contractHealthFilter} onchange={event=>store.contractHealthFilter=event.currentTarget.value}><option value="all">Alle</option><option value="healthy">Gesund</option><option value="degraded">Eingeschränkt</option><option value="blocked">Blockiert</option><option value="unknown">Unbekannt</option></select></label><label><ArrowDownUp size={14}/>Sortierung<select value={store.contractSort} onchange={event=>store.contractSort=event.currentTarget.value as typeof store.contractSort}><option value="name">Name</option><option value="schema">Schema</option><option value="quality">Qualität</option></select></label></div></header><div class="table" role="table" aria-label="Verträge"><div class="head" role="row"><span>Name</span><span>Werte</span><span>Qualität</span><span>Frische</span><span>Verbraucher</span></div>{#each rows as contract(contract.contract_id)}{@const field=Object.keys(contract.values)[0]}{@const quality=contract.field_quality[field]}<button class:selected={store.selectedContractId===contract.contract_id} role="row" onclick={()=>open(contract.contract_id)}><span><strong>{contract.contract_id}</strong><small>{labelForSchema(contract.schema_id)}{store.preferences.technicalNames?` · ${contract.schema_id}`:''}</small></span><span>{field}: <b>{formatValue(contract.values[field])}</b></span><span><StatusBadge status={quality?.health??contract.health}/></span><span><StatusBadge status={quality?.freshness??'unknown'}/></span><span>{store.graph?.fusions.filter(item=>item.contract_id===contract.contract_id).flatMap(item=>item.consumer_ids).length??0}</span></button>{/each}</div></section>{#if selected&&store.preferences.openBehavior==='inspector'}<aside class="inspector" aria-label="Vertrags-Inspector"><div class="inspector-head"><div><small>{selected.schema_id}.v{selected.schema_version}</small><h2>{selected.contract_id}</h2></div><button aria-label="Inspector schließen" onclick={()=>store.selectedContractId=null}>×</button></div><StatusBadge status={selected.health}/><div class="hero">{#each Object.entries(selected.values).slice(0,3) as [field,value]}<div><span>{field}</span><strong>{formatValue(value)}</strong><button onclick={()=>onTrace(selected.contract_id,field)}><HelpCircle size={15}/>Warum?</button></div>{/each}</div><h3>Wichtigste Quellen</h3><p>{Object.values(selected.lineage).flat().join(', ')||'Keine aktive Quelle'}</p><h3>Verbraucher</h3><p>{store.graph?.fusions.filter(item=>item.contract_id===selected.contract_id).flatMap(item=>item.consumer_ids).join(', ')||'Keine deklarierten Verbraucher'}</p><div class="actions"><button onclick={()=>onDetail(selected.contract_id)}><ExternalLink size={16}/>Vollständig öffnen</button><button onclick={onEdit}><Pencil size={16}/>Bearbeiten</button></div></aside>{/if}</div>
<style>
  .explorer{display:grid;grid-template-columns:minmax(0,1fr) minmax(320px,420px);gap:var(--space-4);align-items:start}.list,.inspector{min-width:0;border:1px solid var(--color-border);border-radius:var(--radius-card);background:var(--color-surface);padding:var(--space-4)}header,.inspector-head,.actions,.filters,label{display:flex;align-items:center;gap:var(--space-2)}header,.inspector-head{justify-content:space-between}h2,h3,p{margin:0}header p,small,.inspector p{color:var(--color-text-muted);font-size:.72rem}.filters{flex-wrap:wrap}select,.actions button,.hero button,.inspector-head button{min-height:44px;border:1px solid var(--color-border);border-radius:var(--radius-control);background:var(--color-background);color:var(--color-text-primary);padding:0 var(--space-3)}.table{margin-top:var(--space-4);overflow:hidden}.head,.table>button{display:grid;grid-template-columns:minmax(180px,1.5fr) 1fr .8fr .8fr .6fr;gap:var(--space-3);align-items:center;width:100%;padding:var(--space-3);text-align:left}.head{color:var(--color-text-muted);font-size:.68rem}.table>button{min-height:64px;border:0;border-top:1px solid var(--color-border);background:transparent;color:var(--color-text-primary)}.table>button:hover,.table>button.selected{background:var(--color-info-subtle)}.table span:first-child{display:grid;gap:3px;min-width:0}.hero{display:grid;gap:var(--space-2);margin:var(--space-4) 0}.hero>div{display:grid;grid-template-columns:1fr auto auto;align-items:center;gap:var(--space-2);padding:var(--space-3);border:1px solid var(--color-border);border-radius:var(--radius-control)}.hero span{color:var(--color-text-muted);font-size:.72rem}.hero button,.actions button{display:flex;align-items:center;gap:var(--space-2)}.inspector{position:sticky;top:var(--space-4);display:grid;gap:var(--space-3);max-width:100%}@media(max-width:1100px){.explorer{grid-template-columns:1fr}.inspector{position:static}}@media(max-width:720px){.head{display:none}.table>button{grid-template-columns:1fr 1fr}.table>button span:first-child{grid-column:1/-1}.inspector{position:fixed;z-index:20;inset:8px;overflow:auto}.filters{align-items:stretch}header{align-items:flex-start;flex-direction:column}}
</style>
