<script lang="ts">
  import { ArrowLeft, HelpCircle } from '@lucide/svelte';
  import type { CoreContractsStore } from '../../lib/core-contracts/store.svelte';
  import { formatDateTime, formatValue } from '../../lib/core-contracts/format';
  import { formatRelativeDate } from '../../lib/core-contracts/preferences.svelte';
  import StatusBadge from '../../lib/ui/StatusBadge.svelte';
  let {store,onBack,onTrace}:{store:CoreContractsStore;onBack:()=>void;onTrace:(id:string,field:string)=>void}=$props();
  let tab=$state<'overview'|'fields'|'dependencies'|'usage'|'technical'>('overview');
  let contract=$derived(store.selectedContract); let diagnostic=$derived(store.selectedDiagnostics);
  let fusions=$derived(store.graph?.fusions.filter(item=>item.contract_id===contract?.contract_id)??[]);
  let bindingIds=$derived(new Set(fusions.flatMap(item=>item.input_binding_ids)));
  let bindings=$derived(store.graph?.bindings.filter(item=>bindingIds.has(item.binding_id))??[]);
  const when=(value:string)=>store.preferences.timeDisplay==='relative'?formatRelativeDate(value):store.preferences.timeDisplay==='exact'?formatDateTime(value):`${formatRelativeDate(value)} · ${formatDateTime(value)}`;
</script>

<div class="detail-view"><button class="back" onclick={onBack}><ArrowLeft size={16}/>Zurück zum Explorer</button>{#if contract}<header><div><p class="eyebrow">{contract.schema_id}.v{contract.schema_version}</p><h2>{contract.contract_id}</h2><p>Stand {when(contract.generated_at)}</p></div><StatusBadge status={contract.health}/></header><nav aria-label="Vertragsdetails"><button class:active={tab==='overview'} onclick={()=>tab='overview'}>Überblick</button><button class:active={tab==='fields'} onclick={()=>tab='fields'}>Felder</button><button class:active={tab==='dependencies'} onclick={()=>tab='dependencies'}>Abhängigkeiten</button><button class:active={tab==='usage'} onclick={()=>tab='usage'}>Verwendung</button><button class:active={tab==='technical'} onclick={()=>tab='technical'}>Technische Details</button></nav>
{#if tab==='overview'}<section class="cards">{#each Object.entries(contract.values) as [field,value]}<article><span>{field}</span><strong>{formatValue(value)}</strong><div><StatusBadge status={contract.field_quality[field]?.quality??'unknown'}/><StatusBadge status={contract.field_quality[field]?.freshness??'unknown'}/></div><button onclick={()=>onTrace(contract.contract_id,field)}><HelpCircle size={15}/>Warum?</button></article>{/each}</section>
{:else if tab==='fields'}<section class="stack">{#each Object.keys(contract.field_states) as field}<article><h3>{field}</h3><dl><div><dt>Wert</dt><dd>{formatValue(contract.values[field])}</dd></div><div><dt>Zustand</dt><dd>{contract.field_states[field]}</dd></div><div><dt>Qualität</dt><dd>{contract.field_quality[field]?.quality??'unknown'}</dd></div><div><dt>Frische</dt><dd>{contract.field_quality[field]?.freshness??'unknown'}</dd></div></dl><button onclick={()=>onTrace(contract.contract_id,field)}>Warum?</button></article>{/each}</section>
{:else if tab==='dependencies'}<section class="stack"><h3>Upstream</h3>{#each bindings as binding}<article><strong>{binding.entity_id}</strong>{#if store.preferences.technicalNames}<code>{binding.binding_id}</code>{/if}<p>{binding.field} → {contract.contract_id}</p></article>{:else}<p>Keine konfigurierten Upstream-Quellen.</p>{/each}<h3>Zusammenführungen</h3>{#each fusions as fusion}<article><strong>{fusion.field} · {fusion.strategy}</strong>{#if store.preferences.technicalNames}<code>{fusion.fusion_id}</code>{/if}</article>{:else}<p>Keine Zusammenführung erforderlich.</p>{/each}</section>
{:else if tab==='usage'}<section class="stack">{#each fusions.flatMap(item=>item.consumer_ids) as consumer}<article><strong>{consumer}</strong><p>verwendet {contract.contract_id}</p></article>{:else}<p>Keine deklarierten Verbraucher.</p>{/each}{#each diagnostic?.fields??[] as field}{#if field.consumer_impact?.length}{#each field.consumer_impact as impact}<article><strong>{impact.consumer_id}</strong><p>{field.field} · {impact.status}</p></article>{/each}{/if}{/each}</section>
{:else}<section class="technical"><dl><div><dt>Contract-ID</dt><dd>{contract.contract_id}</dd></div><div><dt>Schema</dt><dd>{contract.schema_id}.v{contract.schema_version}</dd></div><div><dt>Generiert</dt><dd>{formatDateTime(contract.generated_at)}</dd></div><div><dt>Felder</dt><dd>{Object.keys(contract.values).length}</dd></div></dl><details><summary>Typisierter Contract-Payload</summary><pre>{JSON.stringify(contract,null,2)}</pre></details></section>{/if}{:else}<section class="empty"><h2>Vertrag nicht gefunden</h2><p>Der direkte Link verweist auf keinen Vertrag im aktuellen Profil.</p></section>{/if}</div>

<style>
  .detail-view{display:grid;gap:var(--space-5);max-width:1180px;margin:auto}.back,nav,article>div{display:flex;align-items:center;gap:var(--space-2)}button{min-height:44px;padding:0 var(--space-3);border:1px solid var(--color-border);border-radius:var(--radius-control);background:var(--color-surface);color:var(--color-text-primary)}header{display:flex;justify-content:space-between;align-items:flex-start}h2,h3,p{margin:0}header p{color:var(--color-text-muted)}nav{overflow:auto;border-bottom:1px solid var(--color-border)}nav button{flex:0 0 auto;border-color:transparent;background:transparent}nav button.active{border-color:var(--color-info-border);background:var(--color-info-subtle)}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:var(--space-3)}article,.technical,.empty{display:grid;gap:var(--space-3);padding:var(--space-4);border:1px solid var(--color-border);border-radius:var(--radius-card);background:var(--color-surface)}article>span,dt{color:var(--color-text-muted);font-size:.72rem}.stack{display:grid;gap:var(--space-3)}dl{display:grid;gap:var(--space-2);margin:0}dl div{display:flex;justify-content:space-between;gap:var(--space-3)}dd{margin:0;text-align:right}pre{overflow:auto;max-height:420px;font-size:.72rem}@media(max-width:560px){header{flex-direction:column;gap:var(--space-3)}dl div{flex-direction:column}dd{text-align:left}}
</style>
