<script lang="ts">
  import type { AppView, CoreContractsStore } from "../../lib/core-contracts/store.svelte";
  import StatusBadge from "../../lib/ui/StatusBadge.svelte";
  let {store,view}:{store:CoreContractsStore;view:AppView}=$props();
  let bindings=$derived(store.registry.bindings); let fusions=$derived(store.registry.fusions); let devices=$derived(store.registry.devices);
  let missing=$derived(bindings.filter(b=>!b.entity_id||!b.field||!b.capability));
  let staleEntities=$derived(bindings.filter(b=>store.registry.hass&&!store.registry.hass.states?.[b.entity_id]));
  let density=$state("comfortable"), technical=$state(false), time=$state("both"), textSize=$state("system"), motion=$state("system");
</script>

{#if view==="sources"}
  <div class="domain"><div class="tabs"><button class="active">Quellenzuordnungen <b>{bindings.length}</b></button><button>Zusammenführungen <b>{fusions.length}</b></button><button class="primary" onclick={()=>{store.registry.select(null);store.setView("changes")}}>Quelle anlegen</button></div><section class="cards">{#each bindings.filter(b=>`${b.display_name??""} ${b.entity_id} ${b.field}`.toLowerCase().includes(store.search.toLowerCase())) as binding}<article><div><h3>{binding.display_name??binding.entity_id}</h3><small>{binding.entity_id} → {binding.field}</small></div><StatusBadge status={binding.enabled===false?"blocked":"healthy"}/><p>{binding.required?"Pflichtquelle":"Optionale Quelle"} · Frische {binding.freshness_ttl_seconds}s</p><p>Verbraucher: {binding.consumer_ids.join(", ")||"keine"}</p><button onclick={()=>{store.registry.select(binding);store.setView("changes")}}>Details und Bearbeiten</button></article>{/each}</section></div>
{:else if view==="devices"}
  <div class="domain"><section class="cards">{#each devices as device}<article><div><h3>{device.device_id}</h3><small>Technische Geräteidentität</small></div><dl><div><dt>Erwartetes Meldeverhalten</dt><dd>{device.source_cadence}</dd></div><div><dt>Herkunft</dt><dd>{device.cadence_provenance.kind}{device.cadence_provenance.label_id?` · ${device.cadence_provenance.label_id}`:""}</dd></div><div><dt>Intervall</dt><dd>{device.expected_interval_s?`${device.expected_interval_s}s`:"Nicht festgelegt"}</dd></div><div><dt>Lebenszeichen</dt><dd>{device.liveness_entity??"Nicht konfiguriert"}</dd></div></dl><p>{bindings.filter(b=>b.device_id===device.device_id).length} Quellenzuordnungen betroffen</p></article>{:else}<article><h3>Noch keine Geräte</h3><p>Geräte werden beim geführten Anlegen einer Quelle aus der HA-Registry vorgeschlagen und ausdrücklich bestätigt.</p></article>{/each}</section></div>
{:else if view==="setup"}
  <div class="domain"><section class="checks"><article><StatusBadge status={missing.length?"blocked":"healthy"}/><div><h3>Pflichtangaben</h3><p>{missing.length?`${missing.length} Quellen sind unvollständig.`:"Alle Quellen besitzen Entity, Feld und Capability."}</p></div></article><article><StatusBadge status={staleEntities.length?"degraded":"healthy"}/><div><h3>Referenzierte Entities</h3><p>{staleEntities.length?`${staleEntities.length} Entities sind aktuell nicht in Home Assistant vorhanden.`:"Alle prüfbaren Entities sind vorhanden."}</p></div></article><article><StatusBadge status={devices.some(d=>!d.liveness_entity)?"degraded":"healthy"}/><div><h3>Lebenszeichen</h3><p>Geräte ohne Lebenszeichenquelle bleiben sichtbar und können über ihre Quelle ergänzt werden.</p></div></article></section></div>
{:else if view==="settings"}
  <div class="domain settings"><section><h2>Darstellung</h2><label>Ansichtsdichte<select bind:value={density}><option value="comfortable">Komfortabel</option><option value="compact">Kompakt</option></select></label><label>Technische Namen<input type="checkbox" bind:checked={technical}/> zusätzlich anzeigen</label><label>Zeitangaben<select bind:value={time}><option value="relative">Relativ</option><option value="exact">Exakt</option><option value="both">Beides</option></select></label><label>Textgröße<select bind:value={textSize}><option value="system">Systemstandard</option><option value="large">Größer</option><option value="xl">Sehr groß</option></select></label><label>Bewegung reduzieren<select bind:value={motion}><option value="system">Systemeinstellung</option><option value="reduce">Immer reduzieren</option></select></label></section><section><h2>System</h2><dl><div><dt>Datenbankstatus</dt><dd>{store.registry.view?.registry.health??"Nicht verbunden"}</dd></div><div><dt>Schema-Version</dt><dd>{store.registry.view?.registry.revision?.payload.schema_version??"—"}</dd></div><div><dt>Aktive Version</dt><dd>{store.registry.view?.registry.revision?.revision??(store.revision||"—")}</dd></div><div><dt>WebSocket</dt><dd>{store.connectionState}</dd></div><div><dt>Core-Contracts-Version</dt><dd>v0.2.2+</dd></div></dl></section></div>
{/if}

<style>
  .domain{display:grid;gap:var(--space-4)}.tabs{display:flex;flex-wrap:wrap;gap:var(--space-2)}button,select{min-height:44px;padding:0 var(--space-3);border:1px solid var(--color-border);border-radius:var(--radius-control);background:var(--color-surface);color:var(--color-text-primary)}button.active,button.primary{border-color:var(--color-info-border);background:var(--color-info-subtle)}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:var(--space-3)}article,.settings section{display:grid;gap:var(--space-3);padding:var(--space-4);border:1px solid var(--color-border);border-radius:var(--radius-card);background:var(--color-surface)}h2,h3,p{margin:0}small,p,dt{color:var(--color-text-muted)}article>div:first-child{display:grid;gap:4px}.checks{display:grid;gap:var(--space-3)}.checks article{grid-template-columns:auto 1fr;align-items:start}.settings{grid-template-columns:repeat(2,minmax(0,1fr))}.settings label{display:flex;align-items:center;justify-content:space-between;gap:var(--space-3);min-height:44px}dl{display:grid;gap:var(--space-3);margin:0}dl div{display:flex;justify-content:space-between;gap:var(--space-3)}dd{margin:0;text-align:right}@media(max-width:700px){.settings{grid-template-columns:1fr}.settings label{align-items:flex-start;flex-direction:column}select{width:100%}}
</style>
