<script lang="ts">
  import type { RegistryEditor } from '../../lib/core-contracts/registry.svelte';
  let {registry}:{registry:RegistryEditor}=$props();
  const show=(value:unknown)=>value===undefined?'—':typeof value==='object'?JSON.stringify(value):String(value);
</script>
<section class="draft-diff" aria-live="polite"><header><div><p class="eyebrow">Entwurf</p><h2>Änderungen</h2></div><strong>{registry.changeCount===null?'Wird geladen …':`${registry.changeCount} Änderungen`}</strong></header>{#if registry.diffEntries===null}<p>Der aktive Stand wird geladen. Bis dahin wird kein Nullwert behauptet.</p>{:else if registry.diffEntries.length}<div class="rows" role="table" aria-label="Entwurfs-Diff"><div class="head" role="row"><span>Objekt</span><span>Feld</span><span>Vorher</span><span>Neu</span></div>{#each registry.diffEntries as change,index(`${change.kind}:${change.objectId}:${change.field}:${index}`)}<div role="row"><span><strong>{change.objectId}</strong><small>{change.kind} · {change.action}</small></span><code>{change.field}</code><code>{show(change.before)}</code><code>{show(change.after)}</code></div>{/each}</div>{:else}<p>Der Entwurf unterscheidet sich nicht vom aktiven Stand.</p>{/if}</section>
<style>
  .draft-diff{display:grid;gap:var(--space-3);padding:var(--space-4);border:1px solid var(--color-border);border-radius:var(--radius-card);background:var(--color-surface)}header{display:flex;justify-content:space-between;align-items:center}h2,p{margin:0}.rows{overflow:auto}.head,.rows>div{display:grid;grid-template-columns:minmax(180px,1fr) minmax(120px,.6fr) minmax(180px,1fr) minmax(180px,1fr);gap:var(--space-3);padding:var(--space-3);border-top:1px solid var(--color-border)}.head{border:0;color:var(--color-text-muted);font-size:.7rem}.rows span{display:grid;gap:3px}small,code,p{color:var(--color-text-muted);overflow-wrap:anywhere}code{white-space:pre-wrap}@media(max-width:700px){.head{display:none}.rows>div{grid-template-columns:1fr}.rows>div span:first-child{margin-top:var(--space-2)}}
</style>
