<script lang="ts">
  import type { CoreContractsStore } from '../../lib/core-contracts/store.svelte';
  import type { Density, MotionPreference, OpenBehavior, StartView, TextSize, TimeDisplay } from '../../lib/core-contracts/preferences.svelte';
  let {store}:{store:CoreContractsStore}=$props(); let prefs=$derived(store.preferences);
</script>
<div class="settings"><section><h2>Darstellung</h2><label>Ansichtsdichte<select value={prefs.density} onchange={event=>prefs.set('density',event.currentTarget.value as Density)}><option value="comfortable">Komfortabel</option><option value="compact">Kompakt</option></select></label><label>Technische Namen<span><input type="checkbox" checked={prefs.technicalNames} onchange={event=>prefs.set('technicalNames',event.currentTarget.checked)}/> zusätzlich anzeigen</span></label><label>Zeitangaben<select value={prefs.timeDisplay} onchange={event=>prefs.set('timeDisplay',event.currentTarget.value as TimeDisplay)}><option value="relative">Relativ</option><option value="exact">Exakt</option><option value="both">Beides</option></select></label><label>Textgröße<select value={prefs.textSize} onchange={event=>prefs.set('textSize',event.currentTarget.value as TextSize)}><option value="system">Systemstandard</option><option value="large">Größer</option><option value="xlarge">Sehr groß</option></select></label><label>Bewegung reduzieren<select value={prefs.motion} onchange={event=>prefs.set('motion',event.currentTarget.value as MotionPreference)}><option value="system">Systemeinstellung</option><option value="reduce">Immer reduzieren</option></select></label></section><section><h2>Verhalten</h2><label>Startansicht<select value={prefs.startView} onchange={event=>prefs.set('startView',event.currentTarget.value as StartView)}><option value="overview">Übersicht</option><option value="contracts">Verträge</option><option value="last">Letzte Ansicht</option></select></label><label>Datensatzöffnung<select value={prefs.openBehavior} onchange={event=>prefs.set('openBehavior',event.currentTarget.value as OpenBehavior)}><option value="inspector">Inspector</option><option value="detail">Vollständige Detailseite</option></select></label></section><section><h2>System · read-only</h2><dl><div><dt>Datenbankstatus</dt><dd>{store.registry.view?.registry.health??'Nicht verbunden'}</dd></div><div><dt>Schema-Version</dt><dd>{store.registry.view?.registry.revision?.payload.schema_version??'—'}</dd></div><div><dt>Aktive Version</dt><dd>{store.registry.view?.registry.revision?.revision??(store.revision||'—')}</dd></div><div><dt>Entwurf</dt><dd>{store.registry.draft?.draft_id??'Keiner'}</dd></div><div><dt>WebSocket</dt><dd>{store.connectionState}</dd></div></dl></section></div>
<style>
  .settings{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--space-4)}section{display:grid;align-content:start;gap:var(--space-3);padding:var(--space-4);border:1px solid var(--color-border);border-radius:var(--radius-card);background:var(--color-surface)}section:last-child{grid-column:1/-1}h2{margin:0}label,dl div{display:flex;align-items:center;justify-content:space-between;gap:var(--space-3);min-height:44px}select{min-height:44px;padding:0 var(--space-3);border:1px solid var(--color-border);border-radius:var(--radius-control);background:var(--color-background);color:var(--color-text-primary)}dl{display:grid;gap:var(--space-2);margin:0}dt{color:var(--color-text-muted)}dd{margin:0}@media(max-width:700px){.settings{grid-template-columns:1fr}section:last-child{grid-column:auto}label{align-items:flex-start;flex-direction:column}select{width:100%}}
</style>
