<script lang="ts">
  import { ArrowRight } from '@lucide/svelte';
  import type { CoreContractsStore } from '../../lib/core-contracts/store.svelte';
  import StatusBadge from '../../lib/ui/StatusBadge.svelte';
  let {store,onBinding,onDevice,onContract}:{store:CoreContractsStore;onBinding:(id:string)=>void;onDevice:(id:string)=>void;onContract:(id:string,field?:string)=>void}=$props();
  let bindings=$derived(store.registry.bindings); let devices=$derived(store.registry.devices);
  let findings=$derived([
    ...bindings.filter(item=>!item.entity_id||!item.field||!item.capability).map(item=>({id:`binding:${item.binding_id}`,status:'blocked',title:item.display_name??item.binding_id,detail:'Pflichtangaben der Quellenzuordnung fehlen.',action:'Quelle einrichten',run:()=>onBinding(item.binding_id)})),
    ...bindings.filter(item=>store.registry.hass&&!store.registry.hass.states?.[item.entity_id]).map(item=>({id:`entity:${item.binding_id}`,status:'degraded',title:item.display_name??item.entity_id,detail:`Entity ${item.entity_id} existiert aktuell nicht in Home Assistant.`,action:'Entity ersetzen',run:()=>onBinding(item.binding_id)})),
    ...devices.filter(item=>!item.liveness_entity).map(item=>({id:`device:${item.device_id}`,status:'degraded',title:item.device_id,detail:'Für dieses Gerät ist keine Lebenszeichenquelle festgelegt.',action:'Lebenszeichen festlegen',run:()=>onDevice(item.device_id)})),
    ...store.diagnostics.flatMap(contract=>contract.fields.filter(field=>!field.completeness).map(field=>({id:`field:${contract.contract_id}:${field.field}`,status:field.health,title:`${contract.contract_id} · ${field.field}`,detail:field.root_causes[0]?.message??'Pflichtquelle oder verwendbare Evidence fehlt.',action:'Vertragsfeld untersuchen',run:()=>onContract(contract.contract_id,field.field)}))),
  ]);
</script>
<div class="setup"><header><div><h2>Einrichtung prüfen</h2><p>Jeder Fund führt direkt zur betroffenen Stelle und nennt den nächsten Schritt.</p></div><strong>{findings.length} Funde</strong></header>{#if !store.registry.view&&store.registry.busy}<p aria-live="polite">Einrichtung wird geprüft …</p>{:else if store.registry.error}<div role="alert"><StatusBadge status="error"/><p>{store.registry.error.message}</p><button onclick={()=>store.registry.refresh()}>Erneut prüfen</button></div>{:else if findings.length}<section>{#each findings as finding(finding.id)}<article><StatusBadge status={finding.status}/><div><h3>{finding.title}</h3><p>{finding.detail}</p></div><button onclick={finding.run}>{finding.action}<ArrowRight size={15}/></button></article>{/each}</section>{:else}<article class="ok"><StatusBadge status="healthy"/><div><h3>Keine auffällige Einrichtung</h3><p>Alle mit den vorhandenen Daten prüfbaren Abhängigkeiten sind vollständig.</p></div></article>{/if}</div>
<style>
  .setup{display:grid;gap:var(--space-4)}header,article,article button{display:flex;align-items:center;gap:var(--space-3)}header{justify-content:space-between}h2,h3,p{margin:0}p{color:var(--color-text-muted)}section,[role=alert]{display:grid;gap:var(--space-3)}article,[role=alert]{padding:var(--space-4);border:1px solid var(--color-border);border-radius:var(--radius-card);background:var(--color-surface)}article>div{display:grid;gap:4px;flex:1}button{min-height:44px;padding:0 var(--space-3);border:1px solid var(--color-info-border);border-radius:var(--radius-control);background:var(--color-info-subtle);color:var(--color-info-foreground)}@media(max-width:680px){header,article{align-items:flex-start;flex-direction:column}article button{width:100%;justify-content:center}}
</style>
