<script lang="ts">
  import type { CoreContractsStore } from '../../lib/core-contracts/store.svelte';
  import type { Fusion } from '../../lib/core-contracts/types';
  import StatusBadge from '../../lib/ui/StatusBadge.svelte';
  import EmptyState from '../../lib/ui/EmptyState.svelte';
  let {store,onEditBinding,onEditFusion}:{store:CoreContractsStore;onEditBinding:(id?:string)=>void;onEditFusion:(id?:string)=>void}=$props();
  let registry=$derived(store.registry); let bindings=$derived(registry.view?registry.bindings:store.graph?.bindings??[]); let fusions=$derived(registry.view?registry.fusions:store.graph?.fusions??[]);
  let selectedFusion=$derived(fusions.find(item=>item.fusion_id===store.selectedFusionId)??null);
  const chooseFusion=(fusion:Fusion)=>store.selectedFusionId=fusion.fusion_id;
</script>
<div class="sources"><div class="tabs" role="tablist"><button role="tab" aria-selected={store.sourceTab==='bindings'} class:active={store.sourceTab==='bindings'} onclick={()=>store.sourceTab='bindings'}>Quellenzuordnungen <b>{bindings.length}</b></button><button role="tab" aria-selected={store.sourceTab==='fusions'} class:active={store.sourceTab==='fusions'} onclick={()=>store.sourceTab='fusions'}>Zusammenführungen <b>{fusions.length}</b></button>{#if registry.admin}<button class="primary" onclick={()=>store.sourceTab==='bindings'?onEditBinding():onEditFusion()}>{store.sourceTab==='bindings'?'Quelle anlegen':'Zusammenführung anlegen'}</button>{/if}</div>
{#if !registry.view&&!store.graph&&registry.busy}<p aria-live="polite">Quellen werden geladen …</p>{:else if registry.error}<div role="alert"><StatusBadge status="error"/><p>{registry.error.message}</p><button onclick={()=>registry.refresh()}>Erneut laden</button></div>{:else if store.sourceTab==='bindings'}<section class="cards">{#each bindings.filter(item=>`${'display_name'in item?item.display_name??'':''} ${item.entity_id} ${item.field}`.toLowerCase().includes(store.search.toLowerCase())) as binding}<article><div><h3>{'display_name'in binding&&binding.display_name?binding.display_name:binding.entity_id}</h3>{#if store.preferences.technicalNames}<code>{binding.binding_id}</code>{/if}</div><StatusBadge status={'enabled'in binding&&binding.enabled===false?'blocked':'healthy'}/><p>{binding.entity_id} → {binding.field}</p><p>{binding.required?'Pflichtquelle':'Optionale Quelle'} · Frische {binding.freshness_ttl_seconds}s</p><p>Verbraucher: {binding.consumer_ids.join(', ')||'keine'}</p><button onclick={()=>onEditBinding(binding.binding_id)}>Ansehen und bearbeiten</button></article>{:else}<EmptyState title="Keine Quellenzuordnungen" message="Im aktuellen Profil sind keine Quellenzuordnungen vorhanden."/>{/each}</section>
{:else}<div class="fusion-layout"><section class="cards">{#each fusions.filter(item=>`${item.fusion_id} ${item.contract_id} ${item.field} ${item.strategy}`.toLowerCase().includes(store.search.toLowerCase())) as fusion}<article class:selected={selectedFusion?.fusion_id===fusion.fusion_id}><div><h3>{fusion.contract_id} · {fusion.field}</h3>{#if store.preferences.technicalNames}<code>{fusion.fusion_id}</code>{/if}</div><StatusBadge status={store.diagnostics.find(item=>item.contract_id===fusion.contract_id)?.fields.find(item=>item.field===fusion.field)?.health??'unknown'}/><p>Strategie: {fusion.strategy}</p><p>{fusion.input_binding_ids.length} Quellen · {fusion.input_fusion_ids.length} Zusammenführungen</p><div class="actions"><button onclick={()=>chooseFusion(fusion)}>Ansehen</button>{#if registry.admin}<button onclick={()=>onEditFusion(fusion.fusion_id)}>Bearbeiten</button>{/if}</div></article>{:else}<EmptyState title="Keine Zusammenführungen" message="Im aktuellen Profil sind keine Zusammenführungen konfiguriert."/>{/each}</section>{#if selectedFusion}<aside><h2>{selectedFusion.contract_id}.{selectedFusion.field}</h2><p>{selectedFusion.strategy}</p><h3>Eingänge</h3><p>{[...selectedFusion.input_binding_ids,...selectedFusion.input_fusion_ids].join(', ')||'Keine'}</p><h3>Verbraucher</h3><p>{selectedFusion.consumer_ids.join(', ')||'Keine deklarierten Verbraucher'}</p>{#if registry.admin}<button onclick={()=>onEditFusion(selectedFusion.fusion_id)}>Zusammenführung bearbeiten</button>{/if}</aside>{/if}</div>{/if}</div>
<style>
  .sources{display:grid;gap:var(--space-4)}.tabs,.actions{display:flex;flex-wrap:wrap;gap:var(--space-2)}button{min-height:44px;padding:0 var(--space-3);border:1px solid var(--color-border);border-radius:var(--radius-control);background:var(--color-surface);color:var(--color-text-primary)}button.active,button.primary{border-color:var(--color-info-border);background:var(--color-info-subtle)}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:var(--space-3)}article,aside,[role=alert]{display:grid;gap:var(--space-3);padding:var(--space-4);border:1px solid var(--color-border);border-radius:var(--radius-card);background:var(--color-surface)}article.selected{border-color:var(--color-info-border)}h2,h3,p{margin:0}p,code{color:var(--color-text-muted)}.fusion-layout{display:grid;grid-template-columns:minmax(0,1fr) minmax(280px,360px);gap:var(--space-4);align-items:start}aside{position:sticky;top:var(--space-3)}@media(max-width:850px){.fusion-layout{grid-template-columns:1fr}aside{position:static}}
</style>
