<script lang="ts">
  import { ArrowLeft, Check, Clock3, HeartPulse, X } from "@lucide/svelte";
  import type { CoreContractsStore } from "../../lib/core-contracts/store.svelte";
  import { formatDateTime, formatValue, labelForStrategy } from "../../lib/core-contracts/format";
  import StatusBadge from "../../lib/ui/StatusBadge.svelte";
  let {store,onBack}:{store:CoreContractsStore;onBack:()=>void}=$props();
  let contract=$derived(store.selectedContract); let field=$derived(store.selectedField??(contract?Object.keys(contract.values)[0]:null));
  let evaluation=$derived(contract&&field?contract.field_evaluations[field]:null); let quality=$derived(contract&&field?contract.field_quality[field]:null);
  let bindings=$derived(evaluation?store.graph?.bindings.filter(b=>evaluation.candidate_binding_ids.includes(b.binding_id))??[]:[]);
  let signals=$derived(store.graph?.signals.filter(s=>bindings.some(b=>b.binding_id===s.binding_id))??[]);
</script>
<div class="trace"><button class="back" onclick={onBack}><ArrowLeft size={16}/>Zurück zu Verträgen</button>{#if contract&&field&&quality&&evaluation}<header><div><p class="eyebrow">{contract.contract_id}</p><h2>Warum ist „{field}“ so?</h2></div><StatusBadge status={quality.health}/></header><section class="result"><div><span>Aktuelles Ergebnis</span><strong>{formatValue(contract.values[field])}</strong></div><div><span>Qualität</span><StatusBadge status={quality.quality}/></div><div><span>Frische</span><StatusBadge status={quality.freshness}/></div><div><span>Zeitpunkt</span><strong>{formatDateTime(contract.generated_at)}</strong></div></section><section><h3>Kandidaten</h3><div class="candidates">{#each bindings as binding}{@const signal=signals.find(s=>s.binding_id===binding.binding_id)}{@const chosen=evaluation.active_binding_ids.includes(binding.binding_id)}<article class:chosen><div class="decision">{#if chosen}<Check size={18}/><strong>Gewählt</strong>{:else}<X size={18}/><strong>Verworfen</strong>{/if}</div><h4>{binding.entity_id}</h4><dl><div><dt>Wert</dt><dd>{formatValue(signal?.value)}</dd></div><div><dt>Zeitstempelquelle</dt><dd>{signal?.evidence.device_timestamp?"Gerät":"Home Assistant"}</dd></div><div><dt>Gerätezeit</dt><dd>{formatDateTime(signal?.evidence.device_timestamp??null)}</dd></div><div><dt>HA-Zeit</dt><dd>{formatDateTime(signal?.evidence.ha_timestamp??null)}</dd></div><div><dt>Frischegrenze</dt><dd>{binding.freshness_ttl_seconds} Sekunden</dd></div></dl><p>{chosen?"Diese Quelle gehört zum aktuell verwendeten Pfad.":signal?.quality.reasons[0]?.message??"Eine andere Quelle war nach der Strategie geeigneter."}</p></article>{/each}</div></section><section class="explanation"><h3>Entscheidung</h3><p>Die Strategie „{labelForStrategy(evaluation.strategy)}“ hat {evaluation.active_binding_ids.length?"den oben markierten verwendbaren Kandidaten gewählt":"keinen verwendbaren Kandidaten gefunden"}. Der gemeldete Wert ist „{formatValue(contract.values[field])}“. {contract.field_states[field]==="unknown"?"„Unbekannt“ ist hier eine gültige Aussage und wird neutral dargestellt.":"Wert, Qualität und Frische werden getrennt bewertet."}</p><div class="facts"><span><Clock3 size={15}/>Alter und Grenze werden je Quelle ausgewiesen.</span><span><HeartPulse size={15}/>Lebenszeichen und Kadenz stammen aus Geräteprofil oder Binding-Konfiguration, soweit vorhanden.</span></div></section><details><summary>Technische Details</summary><pre>{JSON.stringify({evaluation,quality,signals},null,2)}</pre></details>{:else}<p>Wähle in einem Vertrag bei einem Feld „Warum?“.</p>{/if}</div>
<style>
  .trace{display:grid;gap:var(--space-5);max-width:1100px;margin:auto}.back,.decision,.facts span{display:flex;align-items:center;gap:var(--space-2)}button{min-height:44px;width:max-content;border:1px solid var(--color-border);border-radius:var(--radius-control);background:var(--color-surface);color:var(--color-text-primary);padding:0 var(--space-3)}header{display:flex;justify-content:space-between;align-items:center}h2,h3,h4,p{margin:0}.result{display:grid;grid-template-columns:repeat(4,1fr);gap:var(--space-3)}.result>div,article,.explanation,details{padding:var(--space-4);border:1px solid var(--color-border);border-radius:var(--radius-card);background:var(--color-surface)}.result>div{display:grid;gap:var(--space-2)}.result span,dt{color:var(--color-text-muted);font-size:.7rem}.candidates{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--space-3)}article{display:grid;gap:var(--space-3)}article.chosen{border-color:var(--color-success-border)}dl{display:grid;gap:var(--space-2);margin:0}dl div{display:flex;justify-content:space-between;gap:var(--space-3)}dd{margin:0;text-align:right}.explanation{display:grid;gap:var(--space-3);line-height:1.6}.facts{display:flex;flex-wrap:wrap;gap:var(--space-3);color:var(--color-text-secondary);font-size:.75rem}pre{overflow:auto;max-height:360px;font-size:.72rem}@media(max-width:760px){.result,.candidates{grid-template-columns:1fr 1fr}}@media(max-width:520px){.result,.candidates{grid-template-columns:1fr}}
</style>
